FROM node:12.4.0-stretch-slim as build

WORKDIR /develop

COPY package.json .
COPY yarn.lock .


RUN yarn install

COPY . .
RUN echo "BASE_URL = dev.app.com" > .env
RUN yarn build

# production environment
FROM nginx:1.16.0-alpine
COPY --from=build /develop/dist /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

